# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from . import request_manager_pb2 as request__manager__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in request_manager_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class RequestManagerStub(object):
    """核心服务：请求管理
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRequest = channel.unary_unary(
                '/requestmanager.RequestManager/SubmitRequest',
                request_serializer=request__manager__pb2.SubmitRequestRequest.SerializeToString,
                response_deserializer=request__manager__pb2.SubmitRequestResponse.FromString,
                _registered_method=True)
        self.GetRequestStatus = channel.unary_unary(
                '/requestmanager.RequestManager/GetRequestStatus',
                request_serializer=request__manager__pb2.GetRequestStatusRequest.SerializeToString,
                response_deserializer=request__manager__pb2.GetRequestStatusResponse.FromString,
                _registered_method=True)
        self.CancelRequest = channel.unary_unary(
                '/requestmanager.RequestManager/CancelRequest',
                request_serializer=request__manager__pb2.CancelRequestRequest.SerializeToString,
                response_deserializer=request__manager__pb2.CancelRequestResponse.FromString,
                _registered_method=True)
        self.StreamRequestStatus = channel.unary_stream(
                '/requestmanager.RequestManager/StreamRequestStatus',
                request_serializer=request__manager__pb2.GetRequestStatusRequest.SerializeToString,
                response_deserializer=request__manager__pb2.StatusUpdate.FromString,
                _registered_method=True)
        self.GetQueueStatus = channel.unary_unary(
                '/requestmanager.RequestManager/GetQueueStatus',
                request_serializer=request__manager__pb2.GetQueueStatusRequest.SerializeToString,
                response_deserializer=request__manager__pb2.GetQueueStatusResponse.FromString,
                _registered_method=True)
        self.GetWorkerStatus = channel.unary_unary(
                '/requestmanager.RequestManager/GetWorkerStatus',
                request_serializer=request__manager__pb2.GetWorkerStatusRequest.SerializeToString,
                response_deserializer=request__manager__pb2.GetWorkerStatusResponse.FromString,
                _registered_method=True)
        self.RetryRequest = channel.unary_unary(
                '/requestmanager.RequestManager/RetryRequest',
                request_serializer=request__manager__pb2.RetryRequestRequest.SerializeToString,
                response_deserializer=request__manager__pb2.RetryRequestResponse.FromString,
                _registered_method=True)
        self.Shutdown = channel.unary_unary(
                '/requestmanager.RequestManager/Shutdown',
                request_serializer=request__manager__pb2.ShutdownRequest.SerializeToString,
                response_deserializer=request__manager__pb2.ShutdownResponse.FromString,
                _registered_method=True)
        self.HealthCheck = channel.unary_unary(
                '/requestmanager.RequestManager/HealthCheck',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=request__manager__pb2.HealthCheckResponse.FromString,
                _registered_method=True)


class RequestManagerServicer(object):
    """核心服务：请求管理
    """

    def SubmitRequest(self, request, context):
        """提交请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRequestStatus(self, request, context):
        """获取请求状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelRequest(self, request, context):
        """取消请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamRequestStatus(self, request, context):
        """流式状态更新（Gateway订阅）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetQueueStatus(self, request, context):
        """获取队列状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkerStatus(self, request, context):
        """获取Worker状态
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetryRequest(self, request, context):
        """手动重试请求
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Shutdown(self, request, context):
        """优雅关闭服务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def HealthCheck(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RequestManagerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRequest,
                    request_deserializer=request__manager__pb2.SubmitRequestRequest.FromString,
                    response_serializer=request__manager__pb2.SubmitRequestResponse.SerializeToString,
            ),
            'GetRequestStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRequestStatus,
                    request_deserializer=request__manager__pb2.GetRequestStatusRequest.FromString,
                    response_serializer=request__manager__pb2.GetRequestStatusResponse.SerializeToString,
            ),
            'CancelRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelRequest,
                    request_deserializer=request__manager__pb2.CancelRequestRequest.FromString,
                    response_serializer=request__manager__pb2.CancelRequestResponse.SerializeToString,
            ),
            'StreamRequestStatus': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamRequestStatus,
                    request_deserializer=request__manager__pb2.GetRequestStatusRequest.FromString,
                    response_serializer=request__manager__pb2.StatusUpdate.SerializeToString,
            ),
            'GetQueueStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetQueueStatus,
                    request_deserializer=request__manager__pb2.GetQueueStatusRequest.FromString,
                    response_serializer=request__manager__pb2.GetQueueStatusResponse.SerializeToString,
            ),
            'GetWorkerStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkerStatus,
                    request_deserializer=request__manager__pb2.GetWorkerStatusRequest.FromString,
                    response_serializer=request__manager__pb2.GetWorkerStatusResponse.SerializeToString,
            ),
            'RetryRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.RetryRequest,
                    request_deserializer=request__manager__pb2.RetryRequestRequest.FromString,
                    response_serializer=request__manager__pb2.RetryRequestResponse.SerializeToString,
            ),
            'Shutdown': grpc.unary_unary_rpc_method_handler(
                    servicer.Shutdown,
                    request_deserializer=request__manager__pb2.ShutdownRequest.FromString,
                    response_serializer=request__manager__pb2.ShutdownResponse.SerializeToString,
            ),
            'HealthCheck': grpc.unary_unary_rpc_method_handler(
                    servicer.HealthCheck,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=request__manager__pb2.HealthCheckResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'requestmanager.RequestManager', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('requestmanager.RequestManager', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RequestManager(object):
    """核心服务：请求管理
    """

    @staticmethod
    def SubmitRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/SubmitRequest',
            request__manager__pb2.SubmitRequestRequest.SerializeToString,
            request__manager__pb2.SubmitRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRequestStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/GetRequestStatus',
            request__manager__pb2.GetRequestStatusRequest.SerializeToString,
            request__manager__pb2.GetRequestStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/CancelRequest',
            request__manager__pb2.CancelRequestRequest.SerializeToString,
            request__manager__pb2.CancelRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamRequestStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/requestmanager.RequestManager/StreamRequestStatus',
            request__manager__pb2.GetRequestStatusRequest.SerializeToString,
            request__manager__pb2.StatusUpdate.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetQueueStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/GetQueueStatus',
            request__manager__pb2.GetQueueStatusRequest.SerializeToString,
            request__manager__pb2.GetQueueStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkerStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/GetWorkerStatus',
            request__manager__pb2.GetWorkerStatusRequest.SerializeToString,
            request__manager__pb2.GetWorkerStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetryRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/RetryRequest',
            request__manager__pb2.RetryRequestRequest.SerializeToString,
            request__manager__pb2.RetryRequestResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Shutdown(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/Shutdown',
            request__manager__pb2.ShutdownRequest.SerializeToString,
            request__manager__pb2.ShutdownResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def HealthCheck(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.RequestManager/HealthCheck',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            request__manager__pb2.HealthCheckResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class KernelWorkerStub(object):
    """KernelWorker服务：Python Kernel与Request Manager通信
    Request Manager推送任务流，Kernel直接HTTP回调Gateway
    Kernel只向Request Manager报告心跳和负载
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamTasks = channel.unary_stream(
                '/requestmanager.KernelWorker/StreamTasks',
                request_serializer=request__manager__pb2.WorkerConnectRequest.SerializeToString,
                response_deserializer=request__manager__pb2.KernelTask.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/requestmanager.KernelWorker/Heartbeat',
                request_serializer=request__manager__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=request__manager__pb2.HeartbeatResponse.FromString,
                _registered_method=True)
        self.TaskComplete = channel.unary_unary(
                '/requestmanager.KernelWorker/TaskComplete',
                request_serializer=request__manager__pb2.TaskCompleteRequest.SerializeToString,
                response_deserializer=request__manager__pb2.TaskCompleteResponse.FromString,
                _registered_method=True)


class KernelWorkerServicer(object):
    """KernelWorker服务：Python Kernel与Request Manager通信
    Request Manager推送任务流，Kernel直接HTTP回调Gateway
    Kernel只向Request Manager报告心跳和负载
    """

    def StreamTasks(self, request, context):
        """Kernel连接后，RM通过Server Stream推送任务
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """心跳（用于调度决策）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def TaskComplete(self, request, context):
        """任务完成通知（仅用于调度状态更新，不传递结果）
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KernelWorkerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamTasks': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamTasks,
                    request_deserializer=request__manager__pb2.WorkerConnectRequest.FromString,
                    response_serializer=request__manager__pb2.KernelTask.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=request__manager__pb2.HeartbeatRequest.FromString,
                    response_serializer=request__manager__pb2.HeartbeatResponse.SerializeToString,
            ),
            'TaskComplete': grpc.unary_unary_rpc_method_handler(
                    servicer.TaskComplete,
                    request_deserializer=request__manager__pb2.TaskCompleteRequest.FromString,
                    response_serializer=request__manager__pb2.TaskCompleteResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'requestmanager.KernelWorker', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('requestmanager.KernelWorker', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KernelWorker(object):
    """KernelWorker服务：Python Kernel与Request Manager通信
    Request Manager推送任务流，Kernel直接HTTP回调Gateway
    Kernel只向Request Manager报告心跳和负载
    """

    @staticmethod
    def StreamTasks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/requestmanager.KernelWorker/StreamTasks',
            request__manager__pb2.WorkerConnectRequest.SerializeToString,
            request__manager__pb2.KernelTask.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.KernelWorker/Heartbeat',
            request__manager__pb2.HeartbeatRequest.SerializeToString,
            request__manager__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def TaskComplete(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/requestmanager.KernelWorker/TaskComplete',
            request__manager__pb2.TaskCompleteRequest.SerializeToString,
            request__manager__pb2.TaskCompleteResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
